
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module MyComputer(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
//	input 		          		CLOCK2_50,
//	input 		          		CLOCK3_50,
//	input 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
	//output [7:0] Dout
	//output Dval
	//output [7:0] xo0,xo1,xo2,xo3
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire Debounced_SW_9;
wire [7:0] D_out;
wire [7:0] IP;
wire enable;
//wire [7:0] Dout;
//assign Dout = D_out;
//assign Dout = in;
//assign Dval = enable;


//=======================================================
//  Structural coding
//=======================================================

Debounce debounce (CLOCK_50,SW[9],Debounced_SW_9);
Disp2cNum disp2cnum (D_out,enable,HEX3,HEX2,HEX1,HEX0);
DispHex disphex (IP,HEX4,HEX5);


CPU myCPU (.Din(SW[7:0]),.Sample(~KEY[3]),.Btns(~KEY[2:0]),
.Clock(CLOCK_50),.Reset(Debounced_SW_9),.Turbo(SW[8]),
.Dout(D_out),.Dval(enable),.GPO(LEDR[5:0]),.Debug(LEDR[9:6]),.IP(IP));

endmodule
